# storage-class.yaml
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: etcd-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: etcd-persistent-volume
  labels:
    name: etcd-persistent-volume
spec:
  storageClassName: etcd-local-storage # The persistent volume is directly dependent upon the storage class to fetch volume for the claim
  capacity:
    storage: 1Gi
  local:
    path: /Users/redhood/data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
              - etcd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-volume-claim
  labels:
    app: etcd-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: etcd-local-storage
  resources:
    requests:
      storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  name: etcd-client
spec:
  type: LoadBalancer
  ports:
    - name: etcd-client
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: etcd

---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  selector:
    app: etcd

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  replicas: 3
  template:
    metadata:
      name: etcd
      labels:
        app: etcd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:latest
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          volumeMounts:
            - mountPath: /Users/redhood/data
              name: etcd-volume-claim
          command:
            - /bin/sh
            - -c
            - |
              PEERS="etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380"
              exec etcd --name ${HOSTNAME} \
                --listen-peer-urls http://0.0.0.0:2380 \
                --listen-client-urls http://0.0.0.0:2379 \
                --advertise-client-urls http://${HOSTNAME}.etcd:2379 \
                --initial-advertise-peer-urls http://${HOSTNAME}:2380 \
                --initial-cluster-token etcd-cluster-1 \
                --initial-cluster ${PEERS} \
                --initial-cluster-state new \
                --data-dir /var/run/etcd/default.etcd
      volumes:
        - name: etcd-volume-claim
          persistentVolumeClaim:
            claimName: etcd-volume-claim
  #volumeClaimTemplates:
  #  - metadata:
  #      name: etcd-volume-claim # This is pointing to the volumeMounts inside statefulSet spec
  #    spec:
  #      storageClassName: "etcd-local-storage"
  #      accessModes: [ "ReadWriteOnce" ]
  #      selector:
  #        matchLabels:
  #          name: etcd-persistent-volume
  #      resources:
  #        requests:
  #          storage: 1Gi